name: Morning Telegram Bot
on:
  schedule:
    - cron: "0 22 * * *"  # 05:00 sáng Việt Nam (UTC+7)
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GROUP_CHAT_ID: ${{ secrets.GROUP_CHAT_ID }}
        run: python main.py --once
