services:
  - type: cron
    name: morning-sales-bot
    schedule: "0 0 * * *"   # ⏰ Chạy lúc 07:00 ICT (tương đương 0:00 UTC)
    command: python morning_bot.py --once
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: GROUP_CHAT_ID
        sync: false
