name: Telegram Morning Bot

on:
  schedule:
  - cron: '30 0 * * *'  # Chạy lúc 7h30 sáng giờ Việt Nam (UTC+7)
  workflow_dispatch:     # ✅ Dòng này cho phép chạy thủ công

jobs:
  send_message:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt schedule

    - name: Run bot
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        GROUP_CHAT_ID: ${{ secrets.GROUP_CHAT_ID }}
      run: |
        python telegram_bot.py
